<!-- questions and background can be found here: https://github.com/schatzlab/appliedgenomics2019/tree/master/assignments/assignment5#question-2-time-series-10-pts -->

## Q 2a


```{r}
set.seed(100)
raw_dat = read.table('https://raw.githubusercontent.com/LuchaoQi/hw/master/applied_genomics/hw5/expression.txt',header = 1,row.names = 'name')
raw_dat = as.matrix(raw_dat)


#transpose the data before kmeans!!!
dat = kmeans(t(scale(t(raw_dat))),iter.max=20,centers = 3)
dat
```


Determine the background expression level by taking the average.  

```{r}
apply(raw_dat,2,mean)
```

By looking at the cluster means shown before, we can see:  

Cluster1:decreasing expression  
Cluster3:increasing expression  

Genes of different clusters are shown as below:  
Decreasing: gene_7, gene_14, .... gene_98  
Increasing: gene_5, gene_10, .... gene_100
```{r}
sort(dat$cluster)
```


Visulization:  

```{r}
library(TCseq)
set.seed(100)
raw_dat = read.table('https://raw.githubusercontent.com/LuchaoQi/hw/master/applied_genomics/hw5/expression.txt',header = 1,row.names = 'name')
raw_dat = as.matrix(raw_dat)
dat <- timeclust(raw_dat, algo = "cm", k = 3, standardize = TRUE,iter.max=20) 
#algorithm : fuzzy c means
p <- timeclustplot(dat, categories="time points", cols = 1,axis.text.size = 11)
cluster <- clustCluster(dat)
```



\pagebreak


## Q 2b



```{r}
pca = prcomp(t(raw_dat), scale. = TRUE)
pca$rotation[,1:2]
#screeplot(pca, type="lines",col=3)
```


```{r}
library(tidyverse)
library(ggfortify)
library(cluster)
library(plotly)
pca = prcomp(t(raw_dat), scale. = TRUE)
# PCA = pca$rotation[,1:2]
dftemp = merge(raw_dat,as.data.frame(dat@cluster),by =0,all.x=T) #based on cluster from part(a)
df = dftemp[,-1]
rownames(df) = c(dftemp[,1])
# library(ggfortify)
# autoplot(prcomp(df), data = df, colour = 'dat$cluster')
autoplot(fanny(df[-11], 3), frame = TRUE)
```







